### ISSUE TITLE
Incorrect results of GPU-based BFS algorithm on `graph500-26` dataset

### ISSUE THREAD

**Issue by lilux618** [alibaba/libgrape-lite#116] opened 2022-05-30 07:02 UTC
**Do you have questions or need support? Please describe.**

 I use the GPU program run_cuda_app of libgrape-lite to run the data of graph500--26, the command is ：
`” ./run_cuda_app --application=bfs --lb=cm --bfs_source 62455266 --vfile ../dataset/graph500zst/graph500-26/graph500-26.v --efile ../dataset/graph500zst/graph500-26/graph500-26.e --out_prefix ./output_bfs-26“`

and the results （bfs-output）are as follows. The results are very strange. Is this normal?
<img width="176" alt="image" src="https://user-images.githubusercontent.com/60692776/170934460-9ec224d4-875d-4587-82a6-2335c6226646.png">

**Additional context**
Add any other context about the question here.

**Comment by septicmk** [comment] 2022-05-30 07:16
Hi @lilux618, Thanks for your report, It seems *graph500-26* has only 32,804,978 vertices in this dataset (if you download it from https://ldbcouncil.org/benchmarks/graphalytics/), I guess the bfs_source `62455266` is out-of-range.  this is weird for a `SCALE=26` Kronecker graph, I will check the dataset and reproduce the result as soon as possible.

**Comment by septicmk** [comment] 2022-05-30 09:49
Hi @lilux618, I have tested the *graph500-26* dataset (download it from https://ldbcouncil.org/benchmarks/graphalytics/) in a V100 GPU server. I can not reproduce the bug with your command  and the result is like
```
> head -n15 ./result_frag_0
0 4
1 4
2 4
5 4
6 4
7 3
9 4
10 4
12 4
17 3
18 4
19 4
26 3
29 4
30 4
```

I recommend you update the code to the latest version since recent PRs(#114 #117) introduce massive changes in GPU flow, This bug may have been fixed in these PRs.

**Comment by lilux618** [comment] 2022-05-31 07:17
Thank you! I will test it. I have another two questions: 
1. How to verify the results of BFS application?  In graph500 reference code, the results can be verified by Algorithm [validate](https://graph500.org/?page_id=12#alg:validate). 
2. How can I get a score such as TEPS used in graph500 benchmark according to the output in libgrape-lite? I run libgrape-lite with datatsets graph500-26, and the output is as follow: 
<img width="725" alt="graph500-26" src="https://user-images.githubusercontent.com/60692776/171113877-e992a53f-7feb-4d1a-be59-909c8dacbfaf.png">, it seems the TEPS is as high as 333GTEPS, which is not   
reasonable. Could you please show the results you have run?

**Comment by septicmk** [comment] 2022-05-31 07:47
> How to verify the results of BFS application? In graph500 reference code, the results can be verified by Algorithm [validate](https://graph500.org/?page_id=12#alg:validate).

If you download the dataset from https://ldbcouncil.org/benchmarks/graphalytics/, you will see the correct result (`graph500-26-BFS`) provided by the LDBC benchmark. To validate the result, you can run `md5sum result_frag_0 graph500-26-BFS`. The source vertex of the BFS algorithm used to produce the `graph500-26-BFS` is in `graph500-26.properties`

> How can I get a score such as TEPS used in graph500 benchmark according to the output in libgrape-lite?

TEPS is a metric for graph traversal algorithms like BFS, but it is not appropriate for other algorithms like PR, thus libgrape-lite reports the runtime of algorithms instead of TEPS. To get the TEPS, you can compute `edge_num/runtime`.  If the result of libgrape-lite passes the validation, you may get a reasonable TEPS.

Hope this information may help you reproduce the performance.

**Closed** 2022-05-31 07:48 UTC
Labels: bug
